---

- name: "Playbook variables"
  hosts: linux_servers
  
  vars_files:
    - ./variables/sensible2.yml

  vars:
    mensaje: "Mensaje de playbook"
    curso: "Curso Python - Ansible"
    entornos:
      - testing
      - desarrollo
      - produccion
    responsables: ["Juan", "Maria"]
    desarrollo:
      tipo: linux
      memoria: 8GB
      disco: 80GB
  
  
      
  tasks:
    - name: "Ver variables"
      vars:
        curso: "Curso Python - Ansible en tarea 1"
      debug:
        msg: "Curso: {{ curso }} . Entornos disponibes: {{ entornos }} {{ entornos[0]}} {{ entornos[1:]}} Responsables: {{ responsables }}"
    - name: "Ver variables 2"
      debug:
        msg: "Curso: {{ curso }}. SO: {{ desarrollo }} Capacidad: {{ desarrollo.disco }}"
    - name: "Ver variables 3"
      debug:
        msg: "User: {{ user }} Password: {{  password }}"
